# Generated by Django 2.2 on 2020-07-15 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_point_name', models.CharField(max_length=64)),
                ('salutation_code', models.CharField(max_length=8)),
                ('first_name', models.CharField(max_length=16)),
                ('surname', models.CharField(max_length=16)),
                ('street_name', models.CharField(max_length=32)),
                ('house_number', models.CharField(max_length=8)),
                ('house_number_extended', models.CharField(max_length=8)),
                ('address_supplement', models.CharField(max_length=32)),
                ('extra_address_information', models.CharField(max_length=64)),
                ('zip_code', models.CharField(max_length=16)),
                ('city', models.CharField(max_length=32)),
                ('country_code', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=128)),
                ('company', models.CharField(max_length=64)),
                ('vat_number', models.CharField(max_length=16)),
                ('chamber_of_commerce_number', models.CharField(max_length=16)),
                ('order_reference', models.CharField(max_length=16)),
                ('delivery_phone_number', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pick_up_point', models.BooleanField()),
                ('shipment_date', models.DateTimeField()),
                ('shipment_reference', models.CharField(max_length=16)),
                ('billing_details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_address_shipments', to='shipments.Address')),
                ('customer_details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_shipments', to='shipments.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('client_id', models.CharField(max_length=128)),
                ('client_secret', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('transport_id', models.IntegerField(primary_key=True, serialize=False)),
                ('transporter_code', models.CharField(max_length=8)),
                ('track_and_trace', models.CharField(max_length=32)),
                ('shipping_label_id', models.IntegerField()),
                ('shipping_label_code', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item_id', models.CharField(max_length=16)),
                ('order_id', models.CharField(max_length=16)),
                ('order_date', models.DateTimeField()),
                ('latest_delivery_date', models.DateTimeField()),
                ('ean', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=128)),
                ('quantity', models.IntegerField()),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_condition', models.CharField(max_length=16)),
                ('offer_reference', models.CharField(max_length=16)),
                ('fulfilment_method', models.CharField(choices=[(1, 'FBR'), (2, 'FBB')], max_length=4)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_items', to='shipments.Shipment')),
            ],
        ),
        migrations.AddField(
            model_name='shipment',
            name='shop',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='shipments.Shop'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='transporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='shipments.Transporter'),
        ),
    ]
