# Generated by Django 2.2 on 2020-07-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='latest_delivery_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='shipping_label_code',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='shipping_label_id',
            field=models.IntegerField(null=True),
        ),
    ]
