# Generated by Django 2.2 on 2020-07-15 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_auto_20200715_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_supplement',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='address',
            name='chamber_of_commerce_number',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='address',
            name='company',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='address',
            name='country_code',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='address',
            name='delivery_phone_number',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='address',
            name='extra_address_information',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='address',
            name='house_number_extended',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='address',
            name='order_reference',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='address',
            name='pick_up_point_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='address',
            name='salutation_code',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='address',
            name='surname',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='address',
            name='vat_number',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='billing_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_address_shipments', to='shipments.Address'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='customer_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_shipments', to='shipments.Address'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='pick_up_point',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='ean',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='fulfilment_method',
            field=models.CharField(choices=[(1, 'FBR'), (2, 'FBB')], default='FBR', max_length=4),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='offer_condition',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='offer_reference',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='order_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
