# Generated by Django 2.2 on 2020-07-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_auto_20200715_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentitem',
            name='title',
            field=models.CharField(max_length=512),
        ),
    ]
